api/urls.py
from django.conf.urls import url
from rest_framework import routers
from api import views, viewsets

router = routers.DefaultRouter()
router.register(r'users', viewsets.UserViewSet)
router.register(r'groups', viewsets.GroupViewSet)
router.register(r'table/map', viewsets.TableMapViewSet, base_name='tablemap')
router.register(r'tables', viewsets.TableViewSet, base_name='table')
router.register(r'parties', viewsets.PartyViewSet, base_name='party')
router.register(r'menu/all', viewsets.MenuItemViewSet, base_name='menuall')
router.register(r'menu/categories', viewsets.MenuCategoryViewSet, base_name='menucategory')
router.register(r'menu/items', viewsets.MenuItemByCategoryViewSet, base_name='menuitem')
router.register(r'menu/ingredients', viewsets.MenuIngredientViewSet, base_name='menuingredient')
router.register(r'orders', viewsets.OrderViewSet, base_name='order')

urlpatterns = router.urls
urlpatterns += [
    url(r'^orders/submit$', views.submit_order, name='api-submitorder'),
]

kitchen/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^$', views.orders),
     url(r'^login$', views.login, name='login'),
     url(r'^logout$', views.logout, name='logout'),
     url(r'^map$', views.map, name='map'),
     url(r'^map/edit$', views.map, {'edit': True}, name='map_edit'),
     url(r'^orders$', views.orders, name='orders'),
     url(r'^orders/create$', views.orders_create, name='orders_create'),
     url(r'^orders/clear/(?P<order_id>\d+)?$', views.orders_clear, name='orders_clear'),
     url(r'^menu/(?P<category_id>\d+)?$', views.menu, name='menu'),
     url(r'^menu/ingredients$', views.menu_ingredients, name='menu_ingredients'),
     url(r'^menu/create$', views.menu_create, name='menu_create'),
     url(r'^menu/edit/(?P<edit>\d+)?$', views.menu_create, name='menu_edit'),
     url(r'^menu/category/create$', views.menu_category_create, name='menu_category_create'),
     url(r'^menu/category/edit/(?P<edit>\d+)?$', views.menu_category_create,
         name='menu_category_edit'),
     url(r'^menu/ingredient/create$', views.menu_ingredient_create, name='menu_ingredient_create'),
     url(r'^menu/ingredient/edit/(?P<edit>\d+)?$', views.menu_ingredient_create,
         name='menu_ingredient_edit'),
     url(r'^party/create$', views.party_create, name='party_create'),
     url(r'^party/edit/(?P<edit>\d+)?$', views.party_create, name='party_edit')
]

tablefetchserver/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import api.urls, kitchen.urls
from tablefetchserver import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^api/', include(api.urls.urlpatterns)),
    url(r'^admin/', admin.site.urls),
    url(r'^kitchen/', include(kitchen.urls.urlpatterns))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

api/models.py
from django.db import models

class TableMap(models.Model):
    """ A map to place tables on. """

    name = models.CharField(max_length=256)

    # Width and height give proportions for map image.
    # Will be scaled proportional to browser width.
    width = models.PositiveSmallIntegerField(default=1000)
    height = models.PositiveSmallIntegerField(default=600)

class Table(models.Model):
    """ Representation of a table in the restaurant. """

    table_map = models.ForeignKey(TableMap, on_delete=models.CASCADE, null=True, blank=True)
    num_seats = models.PositiveSmallIntegerField()

    name = models.SlugField(max_length=50)

    current_party = models.OneToOneField('Party', on_delete=models.CASCADE, null=True, related_name='current_table')

    x_coord = models.IntegerField(default=50) # C-coord of corner on map.
    y_coord = models.IntegerField(default=50) # Y-coord of corner on map.
    width = models.IntegerField(default=100) # Width in pixels on map.
    height = models.IntegerField(default=100) # Height in pixels on map.
    color = models.IntegerField(default=0xFFFFFF) # 32-bit RGB hexcolor.

    def __str__(self):
        return self.name

class Party(models.Model):
    """ A party of people sitting at a specified table. """

    table = models.ForeignKey(Table, on_delete=models.CASCADE, null=True, blank=True)

    name = models.CharField(max_length=50, default="")

    size = models.PositiveSmallIntegerField(null=True, blank=True, default=2)
    time_arrived = models.DateTimeField(auto_now_add=True)
    time_seated = models.DateTimeField(null=True, blank=True, default=None)
    time_paid = models.DateTimeField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name

class PartyMember(models.Model):
    """ An individual member of a party. """

    party = models.ForeignKey(Party, on_delete=models.CASCADE)

class MenuCategory(models.Model):
    """ A category for menu items. """

    parent = models.ForeignKey("self", on_delete=models.CASCADE, default=None, null=True,
        blank=True)
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class MenuIngredient(models.Model):
    """ An ingredient on a menu item. (e.g. bread on a sandwhich) """

    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class MenuItem(models.Model):
    """ A choosable menu item. """

    category = models.ManyToManyField(MenuCategory, default=None, blank=True)
    default_ingredients = models.ManyToManyField(MenuIngredient,
        related_name='default_on', blank=True)
    possible_ingredients = models.ManyToManyField(MenuIngredient,
        related_name='possible_on', blank=True)

    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    """ Representation of an order.
    Should be attached to party or party_member. Interface provides
    flexibility to choose to attach order to a single person, or to a
    party as a whole.
    """

    party = models.ForeignKey(Party, on_delete=models.CASCADE, null=True)
    party_member = models.ForeignKey(PartyMember, on_delete=models.CASCADE, null=True)

    time_placed = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    time_finished = models.DateTimeField(default=None, blank=True, null=True)

    menu_items = models.ManyToManyField(MenuItem, through='OrderMenuItem')

class OrderMenuItem(models.Model):
    """ Through model combining order and menu item. """

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem)
    quantity = models.PositiveSmallIntegerField(default=1)

    add_ingredients = models.ManyToManyField(MenuIngredient,
            related_name='added_to', default=None, blank=True)
    remove_ingredients = models.ManyToManyField(MenuIngredient,
            related_name='removed_from', default=None, blank=True)

    comments = models.TextField()

kitchen/models.py
from django.db import models

# Create your models here.

kitchen/forms/menu_item.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import ModelForm

from api.models import MenuItem, MenuCategory, MenuIngredient

class MenuItemForm(ModelForm):
    class Meta:
        model = MenuItem
        fields = ['category', 'name', 'description', 'price',
                'possible_ingredients', 'default_ingredients']

    def __init__(self, *args, **kwargs):
        super(MenuItemForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        
        self.helper.add_input(Submit('submit', 'Submit'))

class MenuIngredientForm(ModelForm):
    class Meta:
        model = MenuIngredient
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs):
        super(MenuIngredientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        self.helper.add_input(Submit('submit', 'Submit'))

class MenuCategoryForm(ModelForm):
    class Meta:
        model = MenuCategory
        fields = ['parent', 'name', 'description']

    def __init__(self, *args, **kwargs):
        super(MenuCategoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        
        self.helper.add_input(Submit('submit', 'Submit'))

kitchen/forms/party.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import ModelForm

from api.models import Party, PartyMember

class PartyForm(ModelForm):
    class Meta:
        model = Party
        fields = ['table', 'name', 'size', 'time_seated', 'time_paid']

    def __init__(self, *args, **kwargs):
        super(PartyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        
        self.helper.add_input(Submit('submit', 'Submit'))

class PartyMemberForm(ModelForm):
    class Meta:
        model = PartyMember
        fields = ['party']

    def __init__(self, *args, **kwargs):
        super(PartyMemberForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        
        self.helper.add_input(Submit('submit', 'Submit'))

kitchen/views.py
from crispy_forms.helper import FormHelper
from datetime import datetime
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from api.models import MenuItem, MenuIngredient, MenuCategory, Order, Table, TableMap, Party, PartyMember
from kitchen.forms.menu_item import MenuItemForm, MenuIngredientForm, MenuCategoryForm
from kitchen.forms.party import PartyForm, PartyMemberForm
from tablefetchserver import helpers

def login(request):
    if request.user.is_authenticated:
        return redirect("map")

    context = {"error": None, "username": ""}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            auth_login(request, user)
            return redirect(request.GET.get("next") or "map")
        else:
            context = {
                "error": "Could not validate those credentials!",
                "username": username
            }

    return render(request, "kitchen/login.html", context)

def logout(request):
    auth_logout(request)
    return redirect("login")

@login_required()
def map(request, edit=False):
    tables = Table.objects.all()

    context = {
        "edit": edit,
        "tables": tables,
        "side_active": "map"
    }
    return render(request, "kitchen/map.html", context)

@login_required()
def orders(request):
    orders = Order.objects.filter(time_finished=None)

    context = {
        "orders": orders,
        "side_active": "orders"
    }
    return render(request, "kitchen/orders.html", context)

@login_required()
def orders_clear(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    order.time_finished = datetime.now()
    order.save()
    return redirect("orders")

@login_required()
def orders_create(request):
    parties = Party.objects.filter(time_paid=None)

    context = {
        "parties": parties,
        "side_active": "orders"
    }
    return render(request, "kitchen/orders_create.html", context)

@login_required()
def menu(request, category_id=None):
    breadcrumbs = []

    if category_id is None:
        category = None
    else:
        category = MenuCategory.objects.get(pk=category_id)
        breadcrumbs.append(category)

        parent = category.parent
        while parent is not None:
            breadcrumbs.append(parent)
            parent = parent.parent

    category_items = MenuCategory.objects.filter(parent=category)
    menu_items = MenuItem.objects.filter(category=category)

    items = []
    for item in category_items:
        items.append({ "type": "category", "obj": item })
    for item in menu_items:
        items.append({ "type": "item", "obj": item })

    context = {
        "side_active": "menu",
        "items": items,
        "category": category,
        "breadcrumbs": breadcrumbs
    }
    return render(request, "kitchen/menu.html", context)

@login_required()
def menu_ingredients(request):
    ingredients = MenuIngredient.objects.all()
    context = {
        "ingredients": ingredients,
        "side_active": "menu"
    }
    return render(request, "kitchen/menu_ingredients.html", context)

@login_required()
def menu_category_create(request, edit=None):
    (success, category, form) = helpers.construct_model_form(MenuCategoryForm, MenuCategory, request, edit)

    context = {
        "category": category,
        "side_active": "menu",
        "success": success,
        "form": form
    }
    return render(request, "kitchen/menu_category_create.html", context)

@login_required()
def menu_ingredient_create(request, edit=None):
    (success, ingredient, form) = helpers.construct_model_form(MenuIngredientForm, MenuIngredient, request, edit)

    context = {
        "ingredient": ingredient,
        "side_active": "menu",
        "success": success,
        "form": form
    }
    return render(request, "kitchen/menu_ingredient_create.html", context)

@login_required()
def menu_create(request, edit=None):
    (success, item, form) = helpers.construct_model_form(MenuItemForm, MenuItem, request, edit)

    context = {
        "item": item,
        "side_active": "menu",
        "success": success,
        "form": form
    }
    return render(request, "kitchen/menu_create.html", context)

@login_required()
def party_create(request, edit=None):
    (success, party, form) = helpers.construct_model_form(PartyForm, Party, request, edit)

    context = {
        "party": party,
        "side_active": "parties",
        "success": success,
        "form": form
    }
    return render(request, "kitchen/party_create.html", context)

kitchen/templates/kitchen/dashboard_base.html
{% load compile_static %}
{% load static %}
<!doctype html>
<html>
<head>
    <title>TableFetch Kitchen{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel='stylesheet' type='text/css'>
    <link href="{% static 'common.scss'|compile %}" rel="stylesheet" type="text/css" />
    {% block cssincludes %}
    {% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="sidebar col-md-2 col-sm-3 p-0">
                <ul class="nav nav-pills flex-column dashboard-menu">
                    <li class="nav-item">
                        <a class="nav-link {% if side_active == "map" %}active{% endif %}" href="{% url 'map' %}">Map</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if side_active == "orders" %}active{% endif %}" href="{% url 'orders' %}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if side_active == "menu" %}active{% endif %}" href="{% url 'menu' %}">Menu</a>
                    </li>
                </ul>
                <ul class="nav flex-column dashboard-menu">
                    <li>
                        <a class="nav-link {% if side_active == "settings" %}active{% endif %}" href="">Settings</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url "logout" %}">Logout</a>
                    </li>
                </ul>
            </nav>
            <div class="dashboard-body col-md-10 offset-md-2 col-sm-9 p-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div style="display: none;" id="templates">
        {% block templates %}{% endblock %}
    </div>

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'tether/dist/js/tether.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js-cookie/src/js.cookie.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>

    {% block scripts %}{% endblock %}
</body>
</html>

kitchen/templates/kitchen/login.html
{% load compile_static %}
{% load static %}

<!doctype html>
<html>
<head>
    <title>TableFetch Kitchen Login</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel='stylesheet' type='text/css'>
    <link href="{% static 'login.scss'|compile %}" rel="stylesheet" type="text/css" />
</head>
<body>

{% if error %}
    <div class="error-container">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert-danger" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <span><strong>Uh oh!</strong> {{ error }}</span>
        </div>
    </div>
{% endif %}

<div class="page-content">
    <div class="login-container">
        <div class="login-box">
            <h3>Kitchen Login</h3>
            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" placeholder="Username" value="{{username}}" required />
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Password" required />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

kitchen/templates/kitchen/map.html
{% extends "kitchen/dashboard_base.html" %}

{% load compile_static %}
{% load static %}

{% block cssincludes %}
<link href="{% static 'map.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<h3 class="table-map-title mb-3"></h3>

<div class="table-map-controls">
    <button type="button" class="switch-mode-btn btn btn-secondary"></button>
    <a href="{% url "party_create" %}" class="btn btn-primary">New Party</a>
    <button type="button" class="new-table-btn btn btn-primary">New Table</button>
</div>

<div class="table-map-div-wrapper">
<svg class="table-map-container{% if edit %} edit-map{% endif %}" style="width: 100%;" viewBox="0 0 1500 900">
    <g class="table-group" style="" ></g>
    <g class="table-label-group" style="font-size: 37;"></g>
</svg>
</div>

<div class="modal fade" id="new-table-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Table</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="slug-field">Slug</label>
                        <input type="text" name="name" class="form-control" id="slug-field" placeholder="Give a short name for your table" required max="10" />
                    </div>
                    <div class="form-group">
                        <label for="party-size-field">Number of seats</label>
                        <input type="number" name="size" class="form-control" id="party-size-field" placeholder="Number of chairs at table" value="4" required />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="table-save-btn btn btn-primary" data-dismiss="modal">Save</button>
                <button class="table-cancel-btn btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="new-party-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Seating <span id="new-party-table-slug"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="currently-seated" style="display: none; text-align: center;">
                    <strong>Currently Seated: <span id="currently-seated-name"></span></strong>
                    <div>
                        <button type="button" id="currently-seated-remove" class="btn btn-danger">Unseat</button>
                    </div>
                    <hr />
                </div>

                <form id="existing-party-form">
                    <div class="form-group">
                        <label for="existing-party">Existing Party</label>
                        <select name="party" class="form-control" id="existing-party-list">
                            <option value="0">Create new party</option>
                        </select>
                    </div>
                </form>

                <hr />
                <div><strong>(OR)</strong></div>
                <hr />

                <form id="create-party-form">
                    <div class="form-group">
                        <label for="name-field">Name</label>
                        <input type="text" name="name" class="form-control" id="name-field" placeholder="Name this party" required max="50" />
                    </div>
                    <div class="form-group">
                        <label for="size-field">Size</label>
                        <input type="number" name="size" class="form-control" id="size-field" placeholder="Size of party" required />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="party-save-btn btn btn-primary">Save</button>
                <button class="party-cancel-btn btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block templates %}
{% endblock %}

{% block scripts %}

<script src="{% static 'js/TableMapManager.js' %}"></script>

<script>

const apiTablesUrl = "{% url "table-list" %}";
const apiPartiesUrl = "{% url "party-list" %}";
const startEditMode = {% if edit %}true{% else %}false{% endif %};

const seatUrl = "{% url "map" %}";
const editUrl = "{% url "map_edit" %}";

const mapManager = new TableMapManager(".table-map-container", apiTablesUrl, apiPartiesUrl, seatUrl, editUrl);

$(function() {
    jqueryAjaxSetup();

    mapManager.loadAllTables();

    if (startEditMode)
        mapManager.enterEditMode();
    else
        mapManager.enterSeatMode();

    mapManager.initListeners();
});

</script>

{% endblock %}

kitchen/templates/kitchen/menu.html
{% extends "kitchen/dashboard_base.html" %}

{% load compile_static %}
{% load static %}

{% block cssincludes %}
<link href="{% static 'menu.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="menu-controls">
    <div class="btn-group" role="group">
        <button id="menu-create-drop" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Create
        </button>
        <div class="dropdown-menu" aria-labelledby="menu-create-drop">
            <a class="dropdown-item" href="{% url 'menu_category_create' %}">Category</a>
            <a class="dropdown-item" href="{% url 'menu_create' %}">Item</a>
        </div>
    </div>

    {% if category %}
        <div class="menu-breadcrumbs btn-group" role="group" aria-label="Category breadcrumbs">
            <a class="btn btn-secondary" href="{% url 'menu' %}">Menu</a>
            {% for bcat in breadcrumbs %}
                <a class="btn btn-secondary" href="{% url "menu" bcat.id %}">{{bcat.name}}</a>
            {% endfor %}
        </div>
    {% endif %}

    <a href="{% url "menu_ingredients" %}" class="btn btn-primary">Ingredients</a>
</div>

<br />

<div id="menu-items">
    <div class="row">
        {% for item in items  %}
            <div class="col-md-3 col-sm-4 menu-item-container">
                {% if item.type == "category" %}
                    <a href="{% url "menu" item.obj.id %}">
                {% else %}
                    <a href="{% url "menu_edit" item.obj.id %}">
                {% endif %}

                <div class="card {% if item.type == "category" %}menu-category-card{%else%}menu-item-card{%endif%}">
                    <div class="card-block">
                        <h4 class="card-title">{{ item.obj.name }}</h4>
                    </div>
                </div>

                {% if item.type == "category" %}
                    </a>
                {% endif %}
            </div>
            {% if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row">
            {% endif %}
        {% empty %}
            <div class="alert alert-info">
                <strong>Nothing here yet!</strong> Create some menu categories and items so that your customers have food to order.
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

kitchen/templates/kitchen/menu_category_create.html
{% extends "kitchen/dashboard_base.html" %}

{% load compile_static %}
{% load static %}

{% load crispy_forms_tags %}

{% block cssincludes %}
<link href="{% static 'menu.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

{% if category %}
    <h3>Editing Category: {{ category.name }}</h3>
{% else %}
    <h3>New Menu Category</h3>
{% endif %}

<br />

{% if success %}
    <div class="alert alert-success" role="alert">
        <strong>Awesome!</strong> Your new category was created.
    </div>
{% endif %}

{% csrf_token %}

{% crispy form %}

{% endblock %}

kitchen/templates/kitchen/menu_create.html
{% extends "kitchen/dashboard_base.html" %}

{% load crispy_forms_tags %}

{% load compile_static %}
{% load static %}

{% block cssincludes %}
<link href="{% static 'menu.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

{% if item %}
    <h3>Editing Item: {{ item.name }}</h3>
{% else %}
    <h3>New Menu Item</h3>
{% endif %}

<br />

{% if success %}
    <div class="alert alert-success" role="alert">
        <strong>Awesome!</strong> Your new item was created.
    </div>
{% endif %}

{% csrf_token %}

{% crispy form %}

{% endblock %}

kitchen/templates/kitchen/menu_ingredient_create.html
{% extends "kitchen/dashboard_base.html" %}

{% load crispy_forms_tags %}

{% block cssincludes %}
<link href="{% static 'menu.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

{% if item %}
    <h3>Editing Ingredient: {{ ingredient.name }}</h3>
{% else %}
    <h3>New Menu Ingredient</h3>
{% endif %}

<br />

{% if success %}
    <div class="alert alert-success" role="alert">
        <strong>Awesome!</strong> Your new ingredient was created.
    </div>
{% endif %}

{% csrf_token %}

{% crispy form %}

{% endblock %}

kitchen/templates/kitchen/orders.html
{% extends "kitchen/dashboard_base.html" %}

{% load compile_static %}
{% load static %}

{% block cssincludes %}
<link href="{% static 'orders.scss'|compile %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="order-controls">
    <a href="{% url 'orders_create' %}" class="btn btn-primary">New Order</a>
</div>

<ol class="orders-list">
    {% for order in orders %}
    <li class="card order" id="order-499394">
        <div class="card-block order-body">
            <h5 class="card-title">
                {{order.party.table.name}} - {{order.party.name}} 
                <span class="text-muted">(#{{order.id}})</span>
            </h5>
            <div class="card-text">
                <ul class="order-item-list">
                    {% for item in order.ordermenuitem_set.all %}
                    <li>{{item.menu_item.name}}
                        {% if item.add_ingredients.count > 0 %}
                        <ul class="order-additions">
                            {% for add_ingredient in item.add_ingredients.all %}
                            <li><span class="order-action-verb">ADD</span> {{add_ingredient.name}}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% if item.remove_ingredients.count > 0 %}
                        <ul class="order-removals">
                            {% for remove_ingredient in item.remove_ingredients.all %}
                            <li><span class="order-action-verb">REMOVE</span> {{remove_ingredient.name}}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="card-footer">
            <div class="order-controls">
                <a href="{% url "orders_clear" order.id %}" class="btn btn-primary btn-sm">Clear</a>
            </div>
        </div>
    </li>
    {% endfor %}
</ol>

{% endblock %}